<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice #{{ $invoice->invoice_number }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 14px;
            color: #333;
            margin: 0;
            padding: 30px;
        }
        .header, .footer {
            width: 100%;
            text-align: center;
        }
        .company-logo {
            max-height: 60px;
            margin-bottom: 10px;
        }
        .invoice-details, .client-details {
            margin: 20px 0;
        }
        .client-details strong {
            display: inline-block;
            width: 100px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 30px;
        }
        table th, table td {
            border: 1px solid #ccc;
            padding: 10px;
        }
        table th {
            background-color: #f4f4f4;
        }
        .total {
            margin-top: 30px;
            text-align: right;
            font-size: 16px;
            font-weight: bold;
        }
        .footer {
            position: fixed;
            bottom: 30px;
            font-size: 12px;
            color: #888;
        }
    </style>
</head>
<body>

<div class="header">
    @if ($invoice->client->user->company_logo)
        <img src="{{ $invoice->client->user->company_logo }}" class="company-logo" alt="Company Logo">
    @endif
    <h2>{{ $invoice->client->user->company_name ?? 'Invoice Generator' }}</h2>
    <p>{{ $invoice->client->user->company_address }}</p>
</div>

<div class="invoice-details">
    <h3>Invoice #{{ $invoice->invoice_number }}</h3>
    <p><strong>Issue Date:</strong> {{ $invoice->issue_date }}</p>
    <p><strong>Due Date:</strong> {{ $invoice->due_date }}</p>
    <p><strong>Status:</strong> {{ ucfirst($invoice->status) }}</p>
</div>

<div class="client-details">
    <h4>Bill To:</h4>
    <p><strong>Name:</strong> {{ $invoice->client->name }}</p>
    <p><strong>Email:</strong> {{ $invoice->client->email }}</p>
    @if($invoice->client->phone)
        <p><strong>Phone:</strong> {{ $invoice->client->phone }}</p>
    @endif
    @if($invoice->client->address)
        <p><strong>Address:</strong> {{ $invoice->client->address }}</p>
    @endif
</div>

<table>
    <thead>
    <tr>
        <th>Description</th>
        <th style="text-align:center;">Qty</th>
        <th style="text-align:right;">Unit Price (AED)</th>
        <th style="text-align:right;">Total (AED)</th>
    </tr>
    </thead>
    <tbody>
    @foreach ($invoice->items as $item)
        <tr>
            <td>{{ $item->description }}</td>
            <td style="text-align:center;">{{ $item->quantity }}</td>
            <td style="text-align:right;">{{ number_format($item->unit_price, 2) }}</td>
            <td style="text-align:right;">{{ number_format($item->total, 2) }}</td>
        </tr>
    @endforeach
    </tbody>
</table>

<div class="total">
    Grand Total: AED {{ number_format($invoice->total, 2) }}
</div>

@if ($invoice->notes)
    <div class="invoice-notes" style="margin-top: 20px;">
        <strong>Notes:</strong>
        <p>{{ $invoice->notes }}</p>
    </div>
@endif

<div class="footer">
    Generated by {{ config('app.name') }} • {{ now()->format('Y-m-d') }}
</div>

</body>
</html>
